[package]
name = "wasm-core"
version = "0.1.0"
edition = "2024"
authors = [
    "i_code_chaos <https://github.com/iCodeChaos>"
]

[lib]
crate-type = ["cdylib"]

[dependencies]
console_log = { version = "1.0.0", features = ["color"] }
log = "0.4.27"
wasm-bindgen = "0.2.100"
